name: flutter_wblock_plugin
description: A Flutter plugin for wBlock content blocking functionality.
version: 1.0.0
homepage: https://github.com/amosogra/flutter_wblock_plugin

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.0.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  plugin:
    platforms:
      ios:
        pluginClass: FlutterWblockPlugin
        # dartPluginClass: FlutterWblockPlugin
      macos:
        pluginClass: FlutterWblockPlugin
        # dartPluginClass: FlutterWblockPlugin
