# Uncomment this line to define a global platform for your project
platform :ios, '17.0'

# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
  unless File.exist?(generated_xcode_build_settings_path)
    raise "#{generated_xcode_build_settings_path} must exist. If you're running pod install manually, make sure flutter pub get is executed first"
  end

  File.foreach(generated_xcode_build_settings_path) do |line|
    matches = line.match(/FLUTTER_ROOT\=(.*)/)
    return matches[1].strip if matches
  end
  raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}. Try deleting Generated.xcconfig, then run flutter pub get"
end

require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)

flutter_ios_podfile_setup

# Add wBlockCoreService from GitHub
# Note: When ready for production, remove the local podspecs and use only this GitHub source
# pod 'wBlockCoreService', :git => 'https://github.com/amosogra/wBlockCoreService_Package.git', :tag => '1.0.0'

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  # 1) CocoaPods will now load your all podspecs from ios/Podspecs
  # TEMPORARY: Using local podspecs for development
  # When ready for production, comment out these lines and uncomment the GitHub source above
  pod 'Punycode', :podspec => '../../ios/Podspecs'
  pod 'FilterEngine', :podspec => '../../ios/Podspecs'
  pod 'PublicSuffixList', :podspec => '../../ios/Podspecs'
  pod 'ContentBlockerConverter', :podspec => '../../ios/Podspecs'
  pod 'ZIPFoundation', :podspec => '../../ios/Podspecs/ZipFoundation.podspec'
  pod 'wBlockCoreService', :podspec => '../../ios/Podspecs'

  # 2) Now bring in everything else (including your plugin):
  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))

  # All wBlock Safari Content Blocker Extensions
  %w[
    wBlock\ Ads
    wBlock\ Scripts
    wBlock\ Privacy
    wBlock\ Security
    wBlock\ Annoyances
    wBlock\ Multipurpose
    wBlock\ Experimental
    wBlock\ Foreign
    wBlock\ Custom
  ].each do |extension_name|
    target extension_name do
      inherit! :search_paths
      pod 'wBlockCoreService', :podspec => '../../ios/Podspecs'
    end
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
  end
end
