platform :osx, '14'

# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'ephemeral', 'Flutter-Generated.xcconfig'), __FILE__)
  unless File.exist?(generated_xcode_build_settings_path)
    raise "#{generated_xcode_build_settings_path} must exist. If you're running pod install manually, make sure \"flutter pub get\" is executed first"
  end

  File.foreach(generated_xcode_build_settings_path) do |line|
    matches = line.match(/FLUTTER_ROOT\=(.*)/)
    return matches[1].strip if matches
  end
  raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}. Try deleting Flutter-Generated.xcconfig, then run \"flutter pub get\""
end

require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)

flutter_macos_podfile_setup

target 'Runner' do
  use_frameworks!

  # 1) CocoaPods will now load your all podspecs from ios/Podspecs
  pod 'Punycode', :podspec => '../../macos/Podspecs'
  pod 'FilterEngine', :podspec => '../../macos/Podspecs'
  pod 'PublicSuffixList', :podspec => '../../macos/Podspecs'
  pod 'ContentBlockerConverter', :podspec => '../../macos/Podspecs'
  pod 'ZIPFoundation', :podspec => '../../macos/Podspecs/ZipFoundation.podspec'
  pod 'wBlockCoreService', :podspec => '../../macos/Podspecs'

  # 2) Now bring in everything else (including your plugin):
  flutter_install_all_macos_pods File.dirname(File.realpath(__FILE__))
  target 'RunnerTests' do
    inherit! :search_paths
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_macos_build_settings(target)
  end
end
